version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: meds_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-medsuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-medspassword}
      POSTGRES_DB: ${DB_NAME:-meds_db}
    ports:
      - "5444:5432"
    volumes:
      - meds_db_data:/var/lib/postgresql/data

  backend:
    build: ./MEDS/backend
    container_name: meds_backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./MEDS/backend:/usr/src/app
      - ./MEDS/ia:/usr/src/ia:ro
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: postgresql://${DB_USER:-medsuser}:${DB_PASSWORD:-medspassword}@db:5432/${DB_NAME:-meds_db}
      PORT: 5000
      JWT_SECRET: ${JWT_SECRET:-supersecretkey}
      NODE_ENV: development
    command: npm run dev
    depends_on:
      - db

  ia:
    build: ./MEDS/ia
    container_name: meds_ia
    restart: always
    volumes:
      - ./MEDS/ia:/usr/src/ia
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USER:-medsuser}
      DB_PASSWORD: ${DB_PASSWORD:-medspassword}
      DB_NAME: ${DB_NAME:-meds_db}
    depends_on:
      - db


volumes:
  meds_db_data:
